# ruff: noqa: E501
"""Self-contained HTML trace visualiser."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from jinja2 import Environment

from autopsyai.models.trace import Trace

if TYPE_CHECKING:
    from autopsyai.models.analysis import TraceAnalysis

_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>autopsyai — {{ trace.name }}</title>
<style>
:root{--bg:#0f172a;--surface:#1e293b;--border:#334155;--text:#e2e8f0;--muted:#94a3b8;--green:#22c55e;--red:#ef4444;--amber:#f59e0b;--sky:#38bdf8;--purple:#a78bfa;}
*{box-sizing:border-box;margin:0;padding:0;}
body{font-family:'Inter',system-ui,sans-serif;background:var(--bg);color:var(--text);padding:2rem;font-size:14px;}
h1{font-size:1.5rem;font-weight:700;color:var(--sky);margin-bottom:.25rem;}
.meta{color:var(--muted);font-size:.85rem;margin-bottom:2rem;}
.stats{display:flex;gap:1rem;flex-wrap:wrap;margin-bottom:2rem;}
.stat{background:var(--surface);border:1px solid var(--border);border-radius:.5rem;padding:.75rem 1.25rem;}
.stat .val{font-size:1.4rem;font-weight:700;}
.stat .lbl{font-size:.75rem;color:var(--muted);}
.span-tree{font-family:monospace;font-size:.85rem;}
.span-row{display:flex;align-items:flex-start;padding:.35rem .5rem;border-radius:.25rem;gap:.5rem;}
.span-row:hover{background:var(--surface);}
.span-name{font-weight:600;}
.span-meta{color:var(--muted);font-size:.78rem;margin-left:.5rem;}
.err{color:var(--red);font-size:.78rem;margin-top:.2rem;margin-left:2rem;}
.badge{display:inline-flex;align-items:center;padding:.15rem .45rem;border-radius:9999px;font-size:.72rem;font-weight:600;}
.ok{background:#14532d;color:var(--green);}
.error{background:#7f1d1d;color:var(--red);}
.findings{margin-top:2rem;}
.finding{display:flex;gap:.75rem;padding:.5rem;border-bottom:1px solid var(--border);font-size:.85rem;}
.sev-critical{color:var(--red);}
.sev-error{color:var(--red);}
.sev-warning{color:var(--amber);}
.sev-info{color:var(--muted);}
footer{margin-top:3rem;color:var(--muted);font-size:.78rem;text-align:center;}
</style>
</head>
<body>
<h1>autopsyai</h1>
<p class="meta">Trace: <strong>{{ trace.name }}</strong> · {{ trace.trace_id }} · {{ trace.started_at.strftime("%Y-%m-%d %H:%M UTC") }}</p>
<div class="stats">
  <div class="stat"><div class="val" style="color:{% if trace.succeeded %}var(--green){% else %}var(--red){% endif %}">{{ trace.status.value.upper() }}</div><div class="lbl">Status</div></div>
  <div class="stat"><div class="val" style="color:var(--sky)">{{ "%.0f"|format(trace.duration_ms) }}ms</div><div class="lbl">Duration</div></div>
  <div class="stat"><div class="val" style="color:var(--sky)">{{ trace.span_count }}</div><div class="lbl">Spans</div></div>
  <div class="stat"><div class="val" style="color:var(--sky)">{{ trace.total_tokens }}</div><div class="lbl">Tokens</div></div>
  {% if analysis %}<div class="stat"><div class="val" style="color:var(--amber)">${{ "%.5f"|format(analysis.total_cost_usd) }}</div><div class="lbl">Est. cost</div></div>{% endif %}
</div>
<div class="span-tree">{{ span_html | safe }}</div>
{% if analysis and analysis.findings %}
<div class="findings">
  <h2 style="margin-bottom:.75rem;color:var(--sky)">Findings ({{ analysis.findings|length }})</h2>
  {% for f in analysis.findings %}
  <div class="finding">
    <span class="sev-{{ f.severity.value }}"><strong>{{ f.severity.value.upper() }}</strong></span>
    <span style="color:var(--purple)">{{ f.code }}</span>
    <span>{{ f.message }}</span>
  </div>
  {% endfor %}
</div>
{% endif %}
<footer>Generated by <strong>autopsyai</strong></footer>
</body></html>"""

_KIND_ICON = {"llm": "🤖", "tool": "🔧", "agent": "🧠", "chain": "⛓", "retrieval": "🔍", "custom": "◆"}


def _render_spans(trace: Trace, parent_id: str | None = None, depth: int = 0) -> str:
    out = []
    spans = [s for s in trace.spans if s.parent_id == parent_id]
    for span in spans:
        icon = _KIND_ICON.get(span.kind.value, "◆")
        status_cls = "error" if span.failed else "ok"
        status_icon = "✗" if span.failed else "✓"
        indent = "&nbsp;" * (depth * 4)
        tok = f"[{span.usage.total_tokens} tok]" if span.usage else ""
        tool = f"tool={span.tool_name}" if span.tool_name else ""
        out.append(
            f'<div class="span-row">'
            f'{indent}<span>{icon}</span>'
            f'<span class="span-name">{span.name}</span>'
            f'<span class="badge {status_cls}">{status_icon}</span>'
            f'<span class="span-meta">{span.duration_ms:.0f}ms {tok} {tool}</span>'
            f'</div>'
        )
        if span.failed and span.error:
            out.append(f'<div class="err">{indent}&nbsp;&nbsp;↳ {span.error[:150]}</div>')
        out.append(_render_spans(trace, parent_id=span.span_id, depth=depth + 1))
    return "\n".join(out)


class HTMLReporter:
    """Renders a self-contained HTML trace report."""

    def __init__(self) -> None:
        env = Environment(autoescape=True)
        self._template = env.from_string(_TEMPLATE)

    def render(self, trace: Trace, analysis: TraceAnalysis | None = None) -> str:
        return self._template.render(
            trace=trace,
            analysis=analysis,
            span_html=_render_spans(trace),
        )

    def write(self, trace: Trace, path: Path, analysis: TraceAnalysis | None = None) -> None:
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        Path(path).write_text(self.render(trace, analysis), encoding="utf-8")
